import React from 'react';
import { Metadata } from 'next'; 
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Schedule App',
  description: 'Generated by By Oksana Fedyukova',
}
const RootLayout: React.FC<{ children: React.ReactNode, metadata: Metadata }> = ({ children, metadata }) => {
  const commonLinks = [
    { url: '/', label: 'Home' },
    { url: '/pages/schedule', label: 'Schedule' },
    { url: '/pages/tasks', label: 'Tasks' }
  ];

  return (
    <html lang="en">
    
    <body className={inter.className}>
        <Navbar links={commonLinks} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
